project16/learning_users/basic_app/urls.py
from django.urls import path, re_path
from . import views

app_name = "basic_app"

urlpatterns = [
    path('register', views.register, name="register"),
    re_path('user_login/$', views.user_login, name="login"),
]

project16/learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    re_path('logout/$', views.user_logout, name="logout"),
    path('basic_app/', include("basic_app.urls")),
    path('special/', views.special, name="special"),
]

project16/learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfoModel(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio_site = models.URLField(max_length=200, blank=True)
    portfolio_pic = models.ImageField(upload_to="portfolio_pics", blank=True)

    def __str__(self):
        return self.user.username

project16/learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfoModel

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ("username", "email", "password")

class UserProfileInfoForm(forms.ModelForm):
    
    class Meta:
        model = UserProfileInfoModel
        fields = ("portfolio_site", "portfolio_pic")

project16/learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def index(request):
    return render(request, "basic_app/index.html")

@login_required
def special(request):
    return HttpResponse("You are logged in, well done!")

@login_required
def user_logout(request):

    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if "profile_pic" in request.FILES:
                profile.profile_pic = request.FILES["profile_pic"]

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, "basic_app/registration.html",
                  {'user_form':user_form,
                   'profile_form': profile_form,
                   'registered': registered})

def user_login(request):

    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse("index"))
            
            else:
                return HttpResponse("Account not active")
        else:
            print("Someone try to login and failed.")
            print("Username:{} and Password:{}".format(username, password))
            return HttpResponse("Invalid login details supplied.")
        
    else:
        return render(request, 'basic_app/login.html', {})

project16/learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'index' %}">D JANGO</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'admin:index' %}">ADMIN</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'basic_app:register' %}">Register</a>
              </li>

              {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'logout' %}">Logout</a>
                </li>
              {% else %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'basic_app:login' %}">Login</a>
                </li>
              {% endif %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
    </nav>
    <div class="container">
        {% block body_content %}
      
        {% endblock body_content %}
    </div>
</body>
</html>

project16/learning_users/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body_content %}
    <div class="bg-body-tertiary p-3 p-sm-5 mb-4">
        <div class="container">
            <h1 class="display-4">Welcome! Django Level five.</h1>
        </div>
    </div>
{% endblock body_content %}

project16/learning_users/templates/basic_app/login.html
{% extends "basic_app/base.html" %}

{% block body_content %}
<div class="bg-body-tertiary p-3 p-sm-5 mb-4">
    <div class="container">
        <h1>Please Login</h1>
        <form action="{% url 'basic_app:login' %}" method="post">
            {% csrf_token %}
            <label for="username">User name:</label>
            <input type="text" name="username" value="" placeholder="Enter username">

            <label for="password">Password:</label>
            <input type="password" name="password">

            <input type="submit" name="" value="Login">
        </form>
    </div>
</div>
{% endblock body_content %}

project16/learning_users/templates/basic_app/registration.html
{% extends "basic_app/base.html" %}
{% load static %}
{% block body_content %}
<div class="bg-body-tertiary p-3 p-sm-5 mb-4">
    <div class="container">
        {% if registered %}
          <h1>Thank you for registering.</h1>
        {% else %}
          <h1>Register here</h1>
          <h3>Fill out the form:</h3>

          <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" name="" value="Register">
          </form>
        {% endif %}
    </div>
</div>
{% endblock body_content %}